# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('vmk_name_alias', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('lin_state', models.CharField(max_length=255)),
                ('transport_identifier', models.CharField(max_length=255)),
                ('bus_info_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('cpu_vendor', models.CharField(max_length=50)),
                ('cpu_code_name', models.CharField(max_length=50)),
                ('cpu_model_name', models.CharField(max_length=50)),
                ('cpu_speed', models.CharField(max_length=50)),
                ('cpu_sockets', models.SmallIntegerField()),
                ('total_cpu_cores', models.SmallIntegerField()),
                ('total_cpu_threads', models.SmallIntegerField()),
                ('memory', models.CharField(max_length=50)),
                ('total_nics', models.SmallIntegerField()),
                ('total_hbas', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('vmk_name_alias', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('driver_version', models.CharField(max_length=255)),
                ('firmware', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start_time', models.DateTimeField()),
                ('reservation_end_time', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservation_tools.Host')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('reservations', models.ManyToManyField(through='lab_reservation_tools.Reservation', to='lab_reservation_tools.Host')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservation_tools.User'),
        ),
    ]
