# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=50)),
                ('nic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start_time', models.DateTimeField()),
                ('reservation_end_time', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservation_tools.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('reservations', models.ManyToManyField(through='lab_reservation_tools.Reservation', to='lab_reservation_tools.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservation_tools.User'),
        ),
        migrations.AddField(
            model_name='device',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservation_tools.Machine'),
        ),
    ]
